### ISSUE TITLE
Assests are not loading properly

### ISSUE THREAD

**Issue by NadhirBenGhorbel** [yasmeene11/Projet_PI-hera-s-haven3A39#1]
[Application] Feb  9 23:41:54 |ERROR  | REQUES Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1:8000/assets/vendor/libs/apex-charts/apex-charts.css" (from "http://127.0.0.1:8000/List_d")" at C:\Users\asus\Desktop\PiDevv\Projet_PI-hera-s-haven3A39\vendor\symfony\http-kernel\EventListener\RouterListener.php line 135
[Web Server ] Feb  9 23:41:55 |WARN   | SERVER GET  (404) /assets/vendor/libs/apex-charts/apex-charts.css ip="127.0.0.1"

**Comment by NuhaRouached** [comment]
Solved Mr Nadhirrrrrr

**Comment by NadhirBenGhorbel** [comment]
My thanks :)
